use crate::project_root;
use anyhow::Result;
use biome_flags::BiomeEnv;
use std::fs;
use std::io::Write;

const HEADER: &str = r#"---
# Don't modify this file manually. It is generated by `codegen/src/env_variables.rs`.

title: Environment variables
description: A list of the environment variables that configure Biome's behavior.
---
The following environment variables configure Biome and its npm package.

"#;

pub fn generate_env_variables() -> Result<()> {
    let file_path = project_root().join("src/content/docs/en/reference/environment-variables.md");

    let mut content = vec![];

    writeln!(content, "{HEADER}")?;
    for variable in BiomeEnv::ENV_VARIABLES {
        writeln!(
            content,
            "## `{}`\n\n{}\n",
            variable.name(),
            variable.description()
        )?;
    }

    fs::write(file_path, content)?;

    Ok(())
}
