use crate::legacy_rule_routes::LEGACY_RULE_ROUTES;
use crate::lintdoc::to_website_language;
use crate::project_root;
use anyhow::Result;
use biome_analyze::{GroupCategory, Queryable, RegistryVisitor, Rule, RuleCategory, RuleGroup};
use biome_css_syntax::CssLanguage;
use biome_graphql_syntax::GraphqlLanguage;
use biome_html_syntax::HtmlLanguage;
use biome_js_syntax::JsLanguage;
use biome_json_syntax::JsonLanguage;
use biome_markdown_syntax::MarkdownLanguage;
use biome_rowan::Language;
use biome_string_case::Case;
use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;

#[derive(Default)]
struct Redirects {
    data: BTreeMap<String, String>,
}

impl Redirects {
    fn push_redirect<R, L>(&mut self)
    where
        L: Language,
        R: Rule<Options: Default, Query: Queryable<Language = L, Output: Clone>> + 'static,
    {
        let rule_name = R::METADATA.name;
        let rule_slug = Case::Kebab.convert(rule_name);
        let path_prefix = if <R::Group as RuleGroup>::Category::CATEGORY == RuleCategory::Action {
            "assist/actions"
        } else {
            "linter/rules"
        };
        let root_path = format!("/{path_prefix}/{rule_slug}");
        let language_path = format!("{root_path}/{}", to_website_language(R::METADATA.language));

        self.data.insert(root_path, language_path.clone());
        self.data
            .insert(format!("/{path_prefix}/{rule_name}"), language_path);
    }
}

impl RegistryVisitor<JsLanguage> for Redirects {
    fn record_rule<R>(&mut self)
    where
        R: Rule<Query: Queryable<Language = JsLanguage, Output: Clone>> + 'static,
    {
        self.push_redirect::<R, JsLanguage>();
    }
}

impl RegistryVisitor<JsonLanguage> for Redirects {
    fn record_rule<R>(&mut self)
    where
        R: Rule<Query: Queryable<Language = JsonLanguage, Output: Clone>> + 'static,
    {
        self.push_redirect::<R, JsonLanguage>();
    }
}

impl RegistryVisitor<CssLanguage> for Redirects {
    fn record_rule<R>(&mut self)
    where
        R: Rule<Query: Queryable<Language = CssLanguage, Output: Clone>> + 'static,
    {
        self.push_redirect::<R, CssLanguage>();
    }
}

impl RegistryVisitor<GraphqlLanguage> for Redirects {
    fn record_rule<R>(&mut self)
    where
        R: Rule<Query: Queryable<Language = GraphqlLanguage, Output: Clone>> + 'static,
    {
        self.push_redirect::<R, GraphqlLanguage>();
    }
}

impl RegistryVisitor<HtmlLanguage> for Redirects {
    fn record_rule<R>(&mut self)
    where
        R: Rule<Query: Queryable<Language = HtmlLanguage, Output: Clone>> + 'static,
    {
        self.push_redirect::<R, HtmlLanguage>();
    }
}

impl RegistryVisitor<MarkdownLanguage> for Redirects {
    fn record_rule<R>(&mut self)
    where
        R: Rule<Query: Queryable<Language = MarkdownLanguage, Output: Clone>> + 'static,
    {
        self.push_redirect::<R, MarkdownLanguage>();
    }
}

pub fn generate_redirects() -> Result<()> {
    let mut redirects = Redirects::default();

    biome_js_analyze::visit_registry(&mut redirects);
    biome_json_analyze::visit_registry(&mut redirects);
    biome_css_analyze::visit_registry(&mut redirects);
    biome_graphql_analyze::visit_registry(&mut redirects);
    biome_html_analyze::visit_registry(&mut redirects);
    biome_markdown_analyze::visit_registry(&mut redirects);

    // Keep the target language of pre-migration URLs stable.
    for &(path_prefix, rule_name, rule_slug, language) in LEGACY_RULE_ROUTES {
        let root_path = format!("/{path_prefix}/{rule_slug}");
        let language_path = format!("{root_path}/{language}");
        redirects.data.insert(root_path, language_path.clone());
        redirects
            .data
            .insert(format!("/{path_prefix}/{rule_name}"), language_path);
    }

    let mut content = String::new();
    content.push_str("// This file is generated by the codegen. Do not edit it manually.\n");
    content.push_str("export default {\n");

    for (from, to) in redirects.data {
        writeln!(content, "  '{from}': '{to}',")?;
    }

    content.push_str("};\n");
    fs::write(project_root().join("redirects.js"), content)?;

    Ok(())
}
