use crate::legacy_rule_routes::LEGACY_RULE_ROUTES;
use crate::project_root;
use anyhow::{Result, ensure};
use std::collections::BTreeMap;
use std::fmt::Write;
use std::fs;

pub fn generate_redirects() -> Result<()> {
    let mut redirects = BTreeMap::new();

    for &(path_prefix, rule_name, rule_slug, language) in LEGACY_RULE_ROUTES {
        let root_path = format!("/{path_prefix}/{rule_slug}");
        let language_path = format!("{root_path}/{language}");
        let target_file = project_root()
            .join("src/content/docs")
            .join(format!("{}.mdx", language_path.trim_start_matches('/')));
        ensure!(
            target_file.exists(),
            "Legacy rule redirect target does not exist: {}",
            target_file.display()
        );

        // Preserve both forms of the rule URLs that existed before explicit
        // language routes. These entries are intentionally sourced from the
        // frozen legacy snapshot instead of the current analyzer registries.
        redirects.insert(root_path, language_path.clone());
        redirects.insert(format!("/{path_prefix}/{rule_name}"), language_path);
    }

    let mut content = String::new();
    content.push_str("// This file is generated by the codegen. Do not edit it manually.\n");
    content.push_str("export default {\n");

    for (from, to) in redirects {
        writeln!(content, "  '{from}': '{to}',")?;
    }

    content.push_str("};\n");
    fs::write(project_root().join("redirects.js"), content)?;

    Ok(())
}
