allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  sharp: false
  tombi: false
linkWorkspacePackages: true
minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.41.2'
  - vite@8.1.2
packages:
  - "scripts"
  - "./"
