name: File change guard

on:
  pull_request:
    branches:
      - main

jobs:
  file-change-guard:
    name: File change guard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Get changed files
        id: changed-files
        continue-on-error: true
        uses: tj-actions/changed-files@0874344d6ebbaa00a27da73276ae7162fadcaf69 # v44.3.0
        with:
          fail_on_submodule_diff_error: true
      - name: Fail the job if the submodule is mutated by users
        if: ${{ steps.changed-files.outcome != 'success' && github.event.pull_request.user.login != 'github-actions[bot]' }}
        run: exit 1
