name: Lunaria

on:
  # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request_target:
    types: [ opened, synchronize ]
    branches: [ main ]

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: depot-ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          # Necessary for Lunaria to work properly
          # Makes the action clone the entire git history
          fetch-depth: 0
          filter: "blob:none"

      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Generate Lunaria Overview
        uses: yanthomasdev/lunaria-action@06ad5ab2704d030708baf3b279ca0446b418e853 # v0.1.0
