name: Lunaria

on:
  # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  pull_request_target:
    types: [ opened, synchronize ]
    branches: [ main ]

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: depot-ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          # Necessary for Lunaria to work properly
          # Makes the action clone the entire git history
          fetch-depth: 0
          filter: "blob:none"

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - name: Generate Lunaria Overview
        uses: yanthomasdev/lunaria-action@06ad5ab2704d030708baf3b279ca0446b418e853 # v0.1.0
